from backend.integrations.ai.base import AIService
from backend.utils.errors import AIServiceError


class NullAIService(AIService):
    def ask_question(self, question: str, context: dict | None = None) -> str:
        if not question.strip():
            raise AIServiceError("AI adapter received an empty question")
        return "This is a placeholder AI response. Replace the adapter with a production AI provider."

    def process_pdf(self, file_path: str) -> dict:
        return {
            "status": "queued",
            "message": "PDF processing adapter is not configured. Replace the AI adapter to execute real ingestion.",
            "file_path": file_path,
        }

    def generate_question_paper(self, topic: str, num_questions: int) -> dict:
        if num_questions <= 0:
            raise AIServiceError("num_questions must be greater than 0")
        return {
            "topic": topic,
            "num_questions": num_questions,
            "paper": [
                {"question": f"Placeholder question {i+1} for {topic}.", "answer": "This answer is generated by a stub adapter."}
                for i in range(num_questions)
            ],
        }
