/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherResourcesRouteImport } from './routes/teacher.resources'
import { Route as TeacherAssistantRouteImport } from './routes/teacher.assistant'
import { Route as TeacherAssessmentsRouteImport } from './routes/teacher.assessments'
import { Route as TeacherAnalyticsRouteImport } from './routes/teacher.analytics'
import { Route as StudentRevisionRouteImport } from './routes/student.revision'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPracticeRouteImport } from './routes/student.practice'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentAssistantRouteImport } from './routes/student.assistant'
import { Route as LoginTeacherRouteImport } from './routes/login.teacher'
import { Route as LoginStudentRouteImport } from './routes/login.student'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResourcesRoute = TeacherResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssistantRoute = TeacherAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssessmentsRoute = TeacherAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnalyticsRoute = TeacherAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentRevisionRoute = StudentRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPracticeRoute = StudentPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssistantRoute = StudentAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => StudentRoute,
} as any)
const LoginTeacherRoute = LoginTeacherRouteImport.update({
  id: '/login/teacher',
  path: '/login/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStudentRoute = LoginStudentRouteImport.update({
  id: '/login/student',
  path: '/login/student',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/login/student': typeof LoginStudentRoute
  '/login/teacher': typeof LoginTeacherRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/revision': typeof StudentRevisionRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/assistant': typeof TeacherAssistantRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/student': typeof LoginStudentRoute
  '/login/teacher': typeof LoginTeacherRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/revision': typeof StudentRevisionRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/assistant': typeof TeacherAssistantRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/login/student': typeof LoginStudentRoute
  '/login/teacher': typeof LoginTeacherRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/revision': typeof StudentRevisionRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/assistant': typeof TeacherAssistantRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/teacher'
    | '/login/student'
    | '/login/teacher'
    | '/student/assistant'
    | '/student/history'
    | '/student/practice'
    | '/student/profile'
    | '/student/revision'
    | '/teacher/analytics'
    | '/teacher/assessments'
    | '/teacher/assistant'
    | '/teacher/resources'
    | '/teacher/settings'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/student'
    | '/login/teacher'
    | '/student/assistant'
    | '/student/history'
    | '/student/practice'
    | '/student/profile'
    | '/student/revision'
    | '/teacher/analytics'
    | '/teacher/assessments'
    | '/teacher/assistant'
    | '/teacher/resources'
    | '/teacher/settings'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/teacher'
    | '/login/student'
    | '/login/teacher'
    | '/student/assistant'
    | '/student/history'
    | '/student/practice'
    | '/student/profile'
    | '/student/revision'
    | '/teacher/analytics'
    | '/teacher/assessments'
    | '/teacher/assistant'
    | '/teacher/resources'
    | '/teacher/settings'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  LoginStudentRoute: typeof LoginStudentRoute
  LoginTeacherRoute: typeof LoginTeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/resources': {
      id: '/teacher/resources'
      path: '/resources'
      fullPath: '/teacher/resources'
      preLoaderRoute: typeof TeacherResourcesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assistant': {
      id: '/teacher/assistant'
      path: '/assistant'
      fullPath: '/teacher/assistant'
      preLoaderRoute: typeof TeacherAssistantRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assessments': {
      id: '/teacher/assessments'
      path: '/assessments'
      fullPath: '/teacher/assessments'
      preLoaderRoute: typeof TeacherAssessmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/analytics': {
      id: '/teacher/analytics'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof TeacherAnalyticsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/revision': {
      id: '/student/revision'
      path: '/revision'
      fullPath: '/student/revision'
      preLoaderRoute: typeof StudentRevisionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/practice': {
      id: '/student/practice'
      path: '/practice'
      fullPath: '/student/practice'
      preLoaderRoute: typeof StudentPracticeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/history': {
      id: '/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assistant': {
      id: '/student/assistant'
      path: '/assistant'
      fullPath: '/student/assistant'
      preLoaderRoute: typeof StudentAssistantRouteImport
      parentRoute: typeof StudentRoute
    }
    '/login/teacher': {
      id: '/login/teacher'
      path: '/login/teacher'
      fullPath: '/login/teacher'
      preLoaderRoute: typeof LoginTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/student': {
      id: '/login/student'
      path: '/login/student'
      fullPath: '/login/student'
      preLoaderRoute: typeof LoginStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentRouteChildren {
  StudentAssistantRoute: typeof StudentAssistantRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentPracticeRoute: typeof StudentPracticeRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRevisionRoute: typeof StudentRevisionRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssistantRoute: StudentAssistantRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentPracticeRoute: StudentPracticeRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRevisionRoute: StudentRevisionRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAnalyticsRoute: typeof TeacherAnalyticsRoute
  TeacherAssessmentsRoute: typeof TeacherAssessmentsRoute
  TeacherAssistantRoute: typeof TeacherAssistantRoute
  TeacherResourcesRoute: typeof TeacherResourcesRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnalyticsRoute: TeacherAnalyticsRoute,
  TeacherAssessmentsRoute: TeacherAssessmentsRoute,
  TeacherAssistantRoute: TeacherAssistantRoute,
  TeacherResourcesRoute: TeacherResourcesRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  LoginStudentRoute: LoginStudentRoute,
  LoginTeacherRoute: LoginTeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
